(() => {
  const DB_NAME = "radiology-ddx-viewer";
  const DB_VERSION = 1;
  const PACK_TYPE = "radiology-ddx-mobile-pack";
  const el = {
    query: document.getElementById("query"), clearButton: document.getElementById("clearButton"),
    results: document.getElementById("results"), details: document.getElementById("details"), chips: document.getElementById("chips"),
    suggestions: document.getElementById("suggestions"), status: document.getElementById("status"), packInput: document.getElementById("packInput"),
    clearPackButton: document.getElementById("clearPackButton"), packMeta: document.getElementById("packMeta"),
    sexButtons: [...document.querySelectorAll(".sex-option")], ageButtons: [...document.querySelectorAll(".age-option")], regionButtons: [...document.querySelectorAll(".region-option")]
  };
  const WEIGHTS = { supportBase: 9, diagnostic: 2.4, importance: 1, prevalence: .15, text: 1.2, exact: 3, conflictBase: 18,
    sex: { female: { female_only: 6, female_predominant: 2, no_sex_predilection: 0, male_predominant: -2, male_only: -14, unknown: 0 }, male: { female_only: -14, female_predominant: -2, no_sex_predilection: 0, male_predominant: 2, male_only: 6, unknown: 0 } },
    age: { strong: 4, partial: 1, mismatch: -4, far: -10, unknown: 0 }, region: { match: 4, organ: 5, mismatch: -2 } };
  const BOOSTS = { "finding:dural_tail_sign": 12, "finding:bridging_vessel_sign": 12, "finding:ring_enhancement": 8, "finding:thick_irregular_ring_enhancement": 12, "finding:open_ring_enhancement": 10, "finding:t2_shading": 10, "finding:fat_present": 11, "finding:central_diffusion_restriction": 9, "finding:vascular_territory_restricted_diffusion": 10, "finding:periventricular_ovoid_lesions": 9 };
  const GENERIC = new Set(["高信号", "軽度高信号", "低信号", "軽度低信号", "等信号", "hyperintensity", "hyperintense", "high signal", "hypointensity", "hypointense", "low signal", "isointensity", "isointense", "hypoattenuation", "mild hypoattenuation", "isoattenuation", "hyperattenuation", "mild hyperattenuation", "低吸収", "軽度低吸収", "等吸収", "高吸収", "軽度高吸収"]);
  const AGE = { child: { label: "小児", min: 0, max: 14 }, young: { label: "若年", min: 15, max: 39 }, middle: { label: "中年", min: 40, max: 64 }, elderly: { label: "高齢", min: 65, max: 120 } };
  const CHIP_GROUPS = [{ title: "CT", groups: [{ title: "吸収値", items: [["脂肪吸収", "fat attenuation"], ["低吸収", "hypoattenuation"], ["軽度低吸収", "mild hypoattenuation"], ["等吸収", "isoattenuation"], ["軽度高吸収", "mild hyperattenuation"], ["高吸収", "hyperattenuation"], ["石灰化", "calcification"]] }] }, { title: "MRI", groups: [{ title: "T1WI", items: [["低信号", "T1 hypointensity"], ["軽度低信号", "mild T1 hypointensity"], ["等信号", "T1 isointensity"], ["軽度高信号", "mild T1 hyperintensity"], ["高信号", "T1 hyperintensity"]] }, { title: "T2WI", items: [["低信号", "T2 hypointensity"], ["軽度低信号", "mild T2 hypointensity"], ["等信号", "T2 isointensity"], ["軽度高信号", "mild T2 hyperintensity"], ["高信号", "T2 hyperintensity"], ["T2 shading", "T2 shading"]] }, { title: "FLAIR", items: [["高信号", "FLAIR hyperintensity"]] }, { title: "DWI / ADC", items: [["DWI高信号", "DWI hyperintensity"], ["DWI等信号", "DWI isointensity"], ["拡散制限あり", "restricted diffusion"], ["拡散制限なし", "no diffusion restriction"], ["ADC低値", "low ADC"], ["ADC等値", "similar ADC"], ["ADC高値", "high ADC"]] }, { title: "造影", items: [["造影効果なし", "no enhancement"], ["軽度造影", "mild enhancement"], ["強い均一造影", "avid homogeneous enhancement"], ["リング状造影", "ring enhancement"], ["open-ring", "open-ring enhancement"]] }] }];
  let db, data, selectedChips = new Map(), selectedSex = "", selectedAge = "", selectedRegion = "", selectedDiseaseId = "", lastResults = [], suggestions = [];
  const norm = (v) => String(v || "").toLowerCase().replace(/\s+/g, " ").trim();
  const esc = (v) => String(v ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  const readable = (v) => { const s = String(v || ""); return s && ((s.match(/[縺繧荳蜿鬮螟]/g) || []).length < Math.max(2, s.length / 5)); };
  const store = (name, mode = "readonly") => db.transaction(name, mode).objectStore(name);
  const idb = (name, method, ...args) => new Promise((resolve, reject) => { const r = store(name, method === "put" || method === "clear" ? "readwrite" : "readonly")[method](...args); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); });
  function openDb() { return new Promise((resolve, reject) => { const r = indexedDB.open(DB_NAME, DB_VERSION); r.onupgradeneeded = () => ["meta", "dictionaries", "search", "summary", "graph", "diseases"].forEach((n) => { if (!r.result.objectStoreNames.contains(n)) r.result.createObjectStore(n); }); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); }); }
  async function putMany(name, entries) { await new Promise((resolve, reject) => { const tx = db.transaction(name, "readwrite"), s = tx.objectStore(name); entries.forEach(([k, v]) => s.put(v, k)); tx.oncomplete = resolve; tx.onerror = () => reject(tx.error); }); }
  async function loadData() { const manifest = await idb("meta", "get", "manifest"); return manifest ? { manifest, dictionaries: await idb("dictionaries", "get", "main"), searchIndex: await idb("search", "get", "items"), summaryIndex: await idb("summary", "get", "items"), differentialGraph: await idb("graph", "get", "main") } : null; }
  async function importPack(file) { setStatus("データ読込中..."); let pack; try { pack = JSON.parse(await file.text()); } catch (e) { throw new Error(`.rddxをJSONとして読めません: ${e.message}`); } validatePack(pack); const counts = pack.manifest.counts || {}, ok = confirm([`${counts.diseases ?? pack.payload.summaryIndex.length}疾患を読み込みます。`, `${counts.searchable_findings ?? pack.payload.searchIndex.length}件の所見indexを保存します。`, "端末内の既存データは置き換えられます。"].join("\n")); if (!ok) return; await clearStores(); await idb("meta", "put", pack.manifest, "manifest"); await idb("dictionaries", "put", pack.payload.dictionaries, "main"); await idb("search", "put", pack.payload.searchIndex, "items"); await idb("summary", "put", pack.payload.summaryIndex, "items"); await idb("graph", "put", pack.payload.differentialGraph, "main"); const cards = []; for (const chunk of pack.payload.diseaseChunks) for (const card of chunk.items || []) cards.push([card.disease_id, card]); await putMany("diseases", cards); data = await loadData(); selectedChips = new Map(); selectedSex = selectedAge = selectedRegion = selectedDiseaseId = ""; suggestions = buildSuggestions(); enableSearch(true); renderAll(); setStatus(`${data.searchIndex.length} findings`); }
  function validatePack(pack) { const errs = []; if (pack?.manifest?.pack_type !== PACK_TYPE) errs.push("対応していない.rddxです。"); if (!pack?.payload?.dictionaries?.findingConcepts) errs.push("findingConceptsがありません。"); if (!Array.isArray(pack?.payload?.searchIndex)) errs.push("searchIndexがありません。"); if (!Array.isArray(pack?.payload?.summaryIndex)) errs.push("summaryIndexがありません。"); if (!Array.isArray(pack?.payload?.diseaseChunks)) errs.push("diseaseChunksがありません。"); if (errs.length) throw new Error(errs.join(" ")); }
  async function clearStores() { for (const n of ["meta", "dictionaries", "search", "summary", "graph", "diseases"]) await idb(n, "clear"); }
  async function clearStoredPack() { if (!confirm("このiPhone内に保存した検索データを削除しますか？")) return; await clearStores(); data = null; suggestions = []; selectedChips = new Map(); selectedSex = selectedAge = selectedRegion = selectedDiseaseId = ""; enableSearch(false); renderAll(); setStatus("データ未読込"); }
  function enableSearch(on) { el.query.disabled = !on; el.clearButton.disabled = !on; [...el.sexButtons, ...el.ageButtons, ...el.regionButtons].forEach((b) => b.disabled = !on); }
  function renderAll() { renderPackMeta(); renderChips(); renderButtons(); renderSuggestions(); resetDetails(); runSearch(); }
  function renderPackMeta() { if (!data) { el.packMeta.textContent = "まだ .rddx は読み込まれていません。OneDrive/ファイルアプリから選択してください。"; return; } const c = data.manifest.counts || {}; el.packMeta.textContent = [`保存済み: ${c.diseases ?? data.summaryIndex.length}疾患`, `${c.searchable_findings ?? data.searchIndex.length}所見`, `作成: ${formatDate(data.manifest.generated_at)}`].join(" / "); }
  function renderChips() { el.chips.innerHTML = ""; if (!data) { el.chips.innerHTML = '<div class="muted">.rddx 読み込み後に所見チップが使えます。</div>'; return; } for (const panel of CHIP_GROUPS) { const details = document.createElement("details"); details.className = "modality-panel"; details.open = panel.groups.some((g) => g.items.some(([, t]) => selectedChips.has(t))); details.innerHTML = `<summary>${esc(panel.title)}</summary>`; const body = document.createElement("div"); body.className = "modality-body"; for (const group of panel.groups) { const wrap = document.createElement("div"); wrap.className = "chip-group"; wrap.innerHTML = `<div class="chip-group-title">${esc(group.title)}</div>`; const row = document.createElement("div"); row.className = "chip-row"; for (const [label, term] of group.items) { const b = document.createElement("button"); b.type = "button"; b.className = `chip${selectedChips.has(term) ? " active" : ""}`; b.textContent = label; b.onclick = () => { selectedChips.has(term) ? selectedChips.delete(term) : selectedChips.set(term, label); renderChips(); runSearch(); }; row.appendChild(b); } wrap.appendChild(row); body.appendChild(wrap); } details.appendChild(body); el.chips.appendChild(details); } }
  function buildQuery() { const rawTerms = new Set([...selectedChips.keys()].map(norm)); const raw = norm(el.query.value); if (raw) { rawTerms.add(raw); raw.split(/[,\s、　]+/).filter(Boolean).forEach((p) => rawTerms.add(norm(p))); } const conceptIds = new Set(), textTerms = new Set(rawTerms); for (const term of rawTerms) for (const id of conceptIdsFromTerm(term)) { conceptIds.add(id); textTerms.add(id); const c = data.dictionaries.findingConcepts[id]; if (c?.canonical_label?.en) textTerms.add(norm(c.canonical_label.en)); if (c?.canonical_label?.ja) textTerms.add(norm(c.canonical_label.ja)); (c?.tokens || []).forEach((t) => { const nt = norm(t); if (!GENERIC.has(nt)) textTerms.add(nt); }); } return { hasInput: rawTerms.size > 0, conceptIds, textTerms: [...textTerms].filter(Boolean) }; }
  function conceptIdsFromTerm(term) { const out = new Set(), concepts = data.dictionaries.findingConcepts || {}, synonyms = data.dictionaries.synonymMap || {}, cs = termConstraints(term); for (const [s, ids] of Object.entries(synonyms)) if (fuzzy(norm(s), term, cs)) ids.forEach((id) => { if (conceptOK(concepts[id], cs)) out.add(id); }); for (const [id, c] of Object.entries(concepts)) { if (!conceptOK(c, cs)) continue; const labels = [id, c?.canonical_label?.en, c?.canonical_label?.ja, ...(c?.tokens || [])].map(norm); if (labels.some((x) => fuzzy(x, term, cs) || x.includes(term) && !(GENERIC.has(term) && !cs.acq.size && !cs.mod))) out.add(id); } return [...out]; }
  function termConstraints(term) { const v = norm(term), acq = new Set(); let mod = ""; const add = (...xs) => xs.forEach((x) => acq.add(x)); if (/\bflair\b/.test(v)) { mod = "MRI"; add("FLAIR"); } if (/\bt1/.test(v)) { mod = "MRI"; add("T1WI"); if (v.includes("contrast") || v.includes("enhanced") || v.includes("ce-t1")) add("contrast_enhanced_T1WI"); } if (/\bt2/.test(v) || v.includes("shading")) { mod = "MRI"; add("T2WI"); if (v.includes("t2*") || v.includes("t2star")) add("T2STAR"); } if (/\bdwi\b/.test(v)) { mod = "MRI"; add("DWI"); } if (/\badc\b/.test(v)) { mod = "MRI"; add("ADC"); } if (v.includes("拡散制限") || v.includes("restricted diffusion")) { mod = "MRI"; add("DWI", "ADC"); } if (/\bswi\b/.test(v) || v.includes("blooming") || v.includes("susceptibility")) { mod = "MRI"; add("SWI", "T2STAR", "GRE_T2STAR"); } if (/\bmra\b/.test(v) || v.includes("tof")) { mod = "MRI"; add("MRA_TOF"); } if (/\bmrv\b/.test(v) || v.includes("venous")) { mod = "MRI"; add("MRV"); } if (/\basl\b/.test(v)) { mod = "MRI"; add("ASL"); } if (v.includes("perfusion") || v.includes("cbv")) { mod = "MRI"; add("DSC_perfusion", "DCE_MRI"); } if (/\bmrs\b/.test(v) || v.includes("choline") || v.includes("lactate") || v.includes("lipid peak")) { mod = "MRI"; add("MRS"); } if (v.includes("opposed-phase") || v.includes("out-of-phase")) { mod = "MRI"; add("DIXON_opposed_phase"); } if (/\bct\b/.test(v) || v.includes("attenuation") || v.includes("吸収") || v.includes("calcification") || v.includes("石灰化")) mod = "CT"; return { mod, acq }; }
  function conceptOK(c, cs) { if (!c) return false; if (cs.mod && c.allowed_modalities?.length && !c.allowed_modalities.includes(cs.mod)) return false; if (cs.acq.size) return (c.allowed_acquisitions || []).some((x) => cs.acq.has(x)); return true; }
  function fuzzy(c, t, cs) { if (!c || !t) return false; if (GENERIC.has(c) && !cs.acq.size && !cs.mod) return false; return c === t || (c.length >= 4 && (c.includes(t) || t.includes(c))); }
  function runSearch() { if (!data) return renderResults([]); const query = buildQuery(); if (!query.hasInput && !selectedSex && !selectedAge && !selectedRegion) return renderResults([]); const by = new Map(); for (const item of data.searchIndex) { const s = scoreFinding(item, query); if (!s.score) continue; const r = by.get(item.disease_id) || { disease_id: item.disease_id, disease_name: item.disease_name, review_status: item.review_status, demographics: item.demographics, prevalence_rank: item.prevalence_rank || 0, score: 0, evidence: [] }; r.score += s.score; r.evidence.push({ ...item, relation: s.relation, score: s.score }); by.set(item.disease_id, r); } for (const r of by.values()) { r.sex_adjustment = sexAdjustment(r.demographics); r.age_adjustment = ageAdjustment(r.demographics); r.score += r.sex_adjustment.score + r.age_adjustment.score; } lastResults = [...by.values()].filter((x) => x.score !== 0).sort((a, b) => b.score - a.score).slice(0, 30); renderResults(lastResults); setStatus(`${lastResults.length} candidates`); }
  function scoreFinding(item, query) { const reg = regionScore(item); if (!query.hasInput) return selectedRegion && reg > 0 ? { relation: "context", score: reg + (item.prevalence_rank || 0) * WEIGHTS.prevalence } : { relation: "context", score: 0 }; const rel = relationFor(item.finding_code, query.conceptIds), txt = textScore(item, query.textTerms), boost = BOOSTS[item.finding_code] || 0; if (rel === "support") return { relation: rel, score: WEIGHTS.supportBase + (item.diagnostic_weight || 0) * WEIGHTS.diagnostic + (item.contextual_importance_rank || 0) * WEIGHTS.importance + (item.prevalence_rank || 0) * WEIGHTS.prevalence + txt * WEIGHTS.text + boost + WEIGHTS.exact + reg }; if (rel === "conflict") return { relation: rel, score: -1 * (WEIGHTS.conflictBase + (item.diagnostic_weight || 0) * WEIGHTS.diagnostic) }; if (!txt && !reg) return { relation: "context", score: 0 }; return { relation: "context", score: txt * WEIGHTS.text + Math.round(boost * .5) + reg + (item.prevalence_rank || 0) * WEIGHTS.prevalence }; }
  function relationFor(code, ids) { if (ids.has(code)) return "support"; for (const id of ids) if ((data.dictionaries.findingConcepts[id]?.opposites || []).includes(code)) return "conflict"; return "context"; }
  function textScore(item, terms) { const hay = norm([item.finding_code, item.canonical_label?.en, item.canonical_label?.ja, item.finding_text, item.modality, item.acquisition_code, item.target, ...Object.values(item.modifiers || {}), ...(item.tokens || [])].filter(Boolean).join(" ")); const tokens = new Set(hay.split(/[^a-z0-9_:+-]+/).filter(Boolean)); return terms.reduce((n, t) => !t || t.startsWith("finding:") ? n : n + (t.length <= 3 ? tokens.has(t) : hay.includes(t) ? 2 : 0), 0); }
  function regionScore(item) { if (!selectedRegion) return 0; const a = item.anatomy || {}, hay = norm([a.body_region, a.organ, a.subregion, item.target, ...(item.tokens || [])].filter(Boolean).join(" ")); if (selectedRegion === "brain") return hay.includes("brain") || hay.includes("meninges") ? WEIGHTS.region.match : WEIGHTS.region.mismatch; if (selectedRegion === "ovary") return hay.includes("ovary") || hay.includes("ovarian") ? WEIGHTS.region.organ : hay.includes("pelvis") || hay.includes("adnexa") ? WEIGHTS.region.match : WEIGHTS.region.mismatch; if (selectedRegion === "pelvis") return hay.includes("pelvis") || hay.includes("ovary") || hay.includes("uterus") || hay.includes("adnexa") ? WEIGHTS.region.match : WEIGHTS.region.mismatch; return 0; }
  function sexAdjustment(d) { if (!selectedSex) return { score: 0, label: "" }; const p = d?.sex?.predilection || "unknown", score = WEIGHTS.sex[selectedSex]?.[p] ?? 0; return { score, label: `性別: ${sexLabel(p)} ${fmt(score)}` }; }
  function ageAdjustment(d) { if (!selectedAge) return { score: 0, label: "" }; const g = AGE[selectedAge], min = d?.age?.typical_min, max = d?.age?.typical_max; if (!g || min == null || max == null) return { score: 0, label: "年齢: 情報なし 0" }; const overlap = Math.max(0, Math.min(max, g.max) - Math.max(min, g.min) + 1), ratio = overlap / (g.max - g.min + 1), gap = g.max < min ? min - g.max : g.min - max, score = ratio >= .5 ? WEIGHTS.age.strong : ratio > 0 ? WEIGHTS.age.partial : gap >= 40 || (g.max <= 14 && min >= 40) || (g.min >= 40 && max <= 14) ? WEIGHTS.age.far : WEIGHTS.age.mismatch; return { score, label: `年齢: ${g.label} / 好発 ${min}-${max}歳 ${fmt(score)}` }; }
  function renderResults(results) { if (!data) { el.results.innerHTML = '<div class="details empty">先に .rddx を読み込んでください。</div>'; return; } if (!results.length) { el.results.innerHTML = '<div class="details empty">所見を入力、またはチップを選択してください。</div>'; return; } el.results.innerHTML = ""; for (const r of results) { const support = r.evidence.filter((x) => x.relation === "support"), conflict = r.evidence.filter((x) => x.relation === "conflict"), context = r.evidence.filter((x) => x.relation === "context"), b = document.createElement("button"); b.type = "button"; b.className = `result-card${r.disease_id === selectedDiseaseId ? " selected" : ""}`; b.innerHTML = `<div class="result-title"><span>${esc(diseaseLabel(r))} ${badge(r.review_status)}</span><span class="score">${r.score.toFixed(1)}</span></div><div class="muted">${esc(r.disease_name?.en || r.disease_id)}</div><div class="match-list">${support.slice(0,3).map((x)=>findingBadge(x,"support")).join("")}${conflict.slice(0,3).map((x)=>findingBadge(x,"conflict")).join("")}${adjBadge(r.sex_adjustment)}${adjBadge(r.age_adjustment)}${context.slice(0,2).map((x)=>findingBadge(x,"context")).join("")}</div>`; b.onclick = async () => { selectedDiseaseId = r.disease_id; await renderDetails(r); renderResults(lastResults); }; el.results.appendChild(b); } }
  async function renderDetails(r) { const card = await idb("diseases", "get", r.disease_id), support = r.evidence.filter((x) => x.relation === "support"), conflict = r.evidence.filter((x) => x.relation === "conflict"), context = r.evidence.filter((x) => x.relation === "context"), related = relatedEdges(r.disease_id); el.details.className = "details"; el.details.innerHTML = `<h3>${esc(diseaseLabel(r))}</h3><p class="muted">${esc(card?.disease_name?.en || r.disease_id)} ${badge(card?.review?.status || r.review_status)}</p>${section("概要", card?.clinical?.overview || card?.frequency?.summary || "未登録")}${section("治療", card?.clinical?.treatment || "未登録")}${section("頻度", `${card?.frequency?.label || "unknown"} / ${card?.frequency?.summary || ""}`)}${section("好発", demo(card?.demographics || r.demographics))}${adjText(r.sex_adjustment)}${adjText(r.age_adjustment)}<div class="section"><strong>検索所見との関係</strong>${evidenceBlock("加点", support, "support")}${evidenceBlock("減点", conflict, "conflict")}${evidenceBlock("文脈一致", context, "context")}</div><div class="section"><strong>関連鑑別</strong>${related.length ? related.map((e)=>graphEdge(e,r.disease_id)).join("") : '<p class="muted">関連疾患グラフにはまだ候補がありません。</p>'}</div><div class="section"><strong>出典</strong>${card?.evidence?.summary ? `<p class="warning">${esc(card.evidence.summary)}</p>` : ""}${refs(card?.references || [])}</div>`; }
  function evidenceBlock(title, items, rel) { return items.length ? `<div class="evidence-block"><div class="evidence-title ${rel}">${esc(title)}</div>${items.map((i)=>`<div class="finding ${rel}"><strong>${esc(findingLabel(i))}</strong><div>${esc(i.finding_text || "")}</div><div class="muted">${esc(i.modality)} / ${esc(i.acquisition_code)} / weight ${esc(i.diagnostic_weight ?? "")} / ${fmt(i.score)}</div></div>`).join("")}</div>` : ""; }
  function buildSuggestions() { if (!data) return []; const m = new Map(), add = (label, value = label, type = "keyword", p = 1) => { label = String(label || "").trim(); value = String(value || "").trim(); const n = norm(value); if (!label || !value || n.length < 3 || n.startsWith("finding:") || GENERIC.has(n)) return; const old = m.get(n); if (!old || p > old.p) m.set(n, { label, value, type, p }); }; for (const [id, c] of Object.entries(data.dictionaries.findingConcepts || {})) { add(c?.canonical_label?.ja, null, "finding", 5); add(c?.canonical_label?.en, null, "finding", 5); for (const list of Object.values(c?.synonyms || {})) for (const s of list || []) add(s, s, "synonym", 4); for (const t of c?.tokens || []) add(t, t, "keyword", 2); add(id, c?.canonical_label?.en || id, "finding", 1); } for (const dictName of ["sequenceMap", "phaseMap"]) for (const [code, x] of Object.entries(data.dictionaries[dictName] || {})) { add(x?.label?.ja, code, dictName === "sequenceMap" ? "sequence" : "CT", 3); add(x?.label?.en, code, dictName === "sequenceMap" ? "sequence" : "CT", 3); for (const s of x?.synonyms || []) add(s, s, dictName === "sequenceMap" ? "sequence" : "CT", 3); } for (const i of data.searchIndex || []) { add(i.finding_text, i.finding_text, "finding", 2); add(i.canonical_label?.ja, null, "finding", 3); add(i.canonical_label?.en, null, "finding", 3); for (const k of i.keywords || []) add(k, k, "keyword", 2); } return [...m.values()].sort((a,b)=>b.p-a.p || a.label.length-b.label.length || a.label.localeCompare(b.label,"ja")); }
  function renderSuggestions() { const q = activeFragment(); if (!el.suggestions || !data || !q || q.length < 2) return hideSuggestions(); const nq = norm(q), hits = suggestions.filter((s)=>norm(s.label).includes(nq) || norm(s.value).includes(nq)).slice(0,8); if (!hits.length) return hideSuggestions(); el.suggestions.innerHTML = hits.map((s)=>`<button type="button" class="suggestion" data-value="${esc(s.value)}"><span>${esc(s.label)}</span><small>${esc(s.type)}</small></button>`).join(""); el.suggestions.hidden = false; }
  function hideSuggestions(){ if(el.suggestions){ el.suggestions.hidden = true; el.suggestions.innerHTML = ""; } }
  function activeFragment(){ const v = el.query.value || "", c = el.query.selectionStart ?? v.length; return (v.slice(0,c).split(/[,\s、　]+/).pop() || ""); }
  function applySuggestion(value){ const cur = el.query.value || "", c = el.query.selectionStart ?? cur.length, before = cur.slice(0,c), after = cur.slice(c), m = before.match(/^(.*?)([^,\s、　]*)$/), prefix = m?.[1] || ""; el.query.value = `${prefix}${value} ${after}`.replace(/\s+/g," ").trimStart(); el.query.focus(); hideSuggestions(); runSearch(); }
  function renderButtons(){ el.sexButtons.forEach((b)=>b.classList.toggle("active", b.dataset.sex === selectedSex)); el.ageButtons.forEach((b)=>b.classList.toggle("active", b.dataset.age === selectedAge)); el.regionButtons.forEach((b)=>b.classList.toggle("active", b.dataset.region === selectedRegion)); }
  function resetDetails(){ selectedDiseaseId=""; el.details.className="details empty"; el.details.textContent = data ? "候補を選択してください。" : "先に .rddx を読み込んでください。"; }
  function relatedEdges(id){ return (data?.differentialGraph?.edges || []).filter((e)=>e.source_disease_id===id || e.target_disease_id===id).sort((a,b)=>(b.similarity_score||0)-(a.similarity_score||0)).slice(0,6); }
  function graphEdge(e,id){ const other = e.source_disease_id === id ? e.target_disease_id : e.source_disease_id, shared = (e.shared_findings || []).map(findingLabel).join(", "); return `<div class="graph-item"><strong>${esc(diseaseName(other))}</strong><div class="muted">similarity ${esc(e.similarity_score ?? "")}</div><div>共有所見: ${esc(shared || "なし")}</div></div>`; }
  function diseaseName(id){ return diseaseLabel(data.summaryIndex.find((x)=>x.disease_id===id) || { disease_id:id }); }
  function diseaseLabel(x){ const ja = x?.disease_name?.ja || "", en = x?.disease_name?.en || ""; return readable(ja) ? ja : en || x?.disease_id || ""; }
  function findingLabel(x){ const ja = x?.canonical_label?.ja || "", en = x?.canonical_label?.en || ""; return readable(ja) ? ja : en || x?.finding_code || ""; }
  function demo(d){ if(!d) return "未登録"; const age = d.age?.typical_min != null && d.age?.typical_max != null ? `${d.age.typical_min}-${d.age.typical_max}歳` : ""; return [sexLabel(d.sex?.predilection), age, d.age?.peak_decade ? `peak ${d.age.peak_decade}` : ""].filter(Boolean).join(" / ") || "未登録"; }
  function sexLabel(v){ return ({ female_only:"女性のみ", female_predominant:"女性に多い", no_sex_predilection:"性差なし", male_predominant:"男性に多い", male_only:"男性のみ", unknown:"性差不明" })[v] || v || "性差不明"; }
  function refs(items){ return items.length ? `<ul class="reference-list">${items.slice(0,8).map((r)=>`<li>${esc(r.title || r.source_id || "")} ${r.url ? `<a href="${esc(r.url)}" target="_blank" rel="noopener">link</a>` : ""}</li>`).join("")}</ul>` : '<p class="muted">出典未登録</p>'; }
  function section(t,b){ return `<div class="section"><strong>${esc(t)}</strong><p>${esc(b || "")}</p></div>`; }
  function badge(s){ return !s || s === "approved" ? "" : `<span class="review-badge">${esc(s)}</span>`; }
  function findingBadge(i,rel){ return `<span class="match ${rel}">${rel === "support" ? "加点" : rel === "conflict" ? "減点" : "一致"}: ${esc(findingLabel(i))}</span>`; }
  function adjBadge(a){ if(!a?.label) return ""; return `<span class="match ${a.score > 0 ? "adjust-positive" : a.score < 0 ? "adjust-negative" : "sex"}">${esc(a.label)}</span>`; }
  function adjText(a){ if(!a?.label) return ""; return `<p class="${a.score > 0 ? "support-text" : a.score < 0 ? "conflict-text" : "muted"}">補正: ${esc(a.label)}</p>`; }
  function formatDate(v){ const d = new Date(v); return v && !Number.isNaN(d.getTime()) ? d.toLocaleString("ja-JP") : "不明"; }
  function fmt(v){ const n = Number(v || 0); return `${n > 0 ? "+" : ""}${n.toFixed(1)}`; }
  function setStatus(s){ el.status.textContent = s; }
  el.packInput.addEventListener("change", async()=>{ const f=el.packInput.files?.[0]; if(!f) return; try{ await importPack(f); } catch(e){ setStatus("読込失敗"); alert(e.message); } finally { el.packInput.value=""; } });
  el.clearPackButton.addEventListener("click",()=>clearStoredPack().catch((e)=>alert(e.message)));
  el.query.addEventListener("input",()=>{ renderSuggestions(); runSearch(); }); el.query.addEventListener("focus", renderSuggestions);
  el.clearButton.addEventListener("click",()=>{ el.query.value=""; selectedChips=new Map(); selectedSex=selectedAge=selectedRegion=""; hideSuggestions(); renderAll(); });
  el.suggestions?.addEventListener("pointerdown",(e)=>{ const b=e.target.closest(".suggestion"); if(!b) return; e.preventDefault(); applySuggestion(b.dataset.value || ""); });
  document.addEventListener("pointerdown",(e)=>{ if(e.target===el.query || el.suggestions?.contains(e.target)) return; hideSuggestions(); });
  el.sexButtons.forEach((b)=>b.onclick=()=>{ selectedSex=b.dataset.sex || ""; renderButtons(); runSearch(); });
  el.ageButtons.forEach((b)=>b.onclick=()=>{ selectedAge=b.dataset.age || ""; renderButtons(); runSearch(); });
  el.regionButtons.forEach((b)=>b.onclick=()=>{ selectedRegion=b.dataset.region || ""; renderButtons(); runSearch(); });
  async function init(){ try{ db=await openDb(); data=await loadData(); suggestions=buildSuggestions(); enableSearch(Boolean(data)); renderAll(); if(data) setStatus(`${data.searchIndex.length} findings`); } catch(e){ setStatus("初期化失敗"); el.packMeta.textContent=e.message; } if("serviceWorker" in navigator && location.protocol !== "file:") navigator.serviceWorker.register("sw.js").catch(()=>{}); }
  init();
})();
